/*
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Bin model module.
 * @module model/Bin
 * @version 1.0.0
 */
export class Bin {
  /**
   * Constructs a new <code>Bin</code>.
   * @alias module:model/Bin
   * @class
   * @param bin {String} 
   */
  constructor(bin) {
    this.bin = bin;
  }

  /**
   * Constructs a <code>Bin</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Bin} obj Optional instance to populate.
   * @return {module:model/Bin} The populated <code>Bin</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Bin();
      if (data.hasOwnProperty('bin'))
        obj.bin = ApiClient.convertToType(data['bin'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} bin
 */
Bin.prototype.bin = undefined;

