/*
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Description model module.
 * @module model/Description
 * @version 1.0.0
 */
export class Description {
  /**
   * Constructs a new <code>Description</code>.
   * @alias module:model/Description
   * @class
   * @param description {String} 
   */
  constructor(description) {
    this.description = description;
  }

  /**
   * Constructs a <code>Description</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Description} obj Optional instance to populate.
   * @return {module:model/Description} The populated <code>Description</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Description();
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} description
 */
Description.prototype.description = undefined;

