/*
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Bin} from './Bin';
import {Description} from './Description';
import {Manufacturer} from './Manufacturer';
import {Quantity} from './Quantity';
import {Units} from './Units';

/**
 * The InventoryItem model module.
 * @module model/InventoryItem
 * @version 1.0.0
 */
export class InventoryItem {
  /**
   * Constructs a new <code>InventoryItem</code>.
   * @alias module:model/InventoryItem
   * @class
   * @param id {String} 
   * @param name {String} 
   * @param releaseDate {Date} 
   * @param manufacturer {module:model/Manufacturer} 
   * @param quantity {module:model/Quantity} 
   * @param description {module:model/Description} 
   * @param units {module:model/Units} 
   * @param bin {module:model/Bin} 
   */
  constructor(id, name, releaseDate, manufacturer, quantity, description, units, bin) {
    this.id = id;
    this.name = name;
    this.releaseDate = releaseDate;
    this.manufacturer = manufacturer;
    this.quantity = quantity;
    this.description = description;
    this.units = units;
    this.bin = bin;
  }

  /**
   * Constructs a <code>InventoryItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InventoryItem} obj Optional instance to populate.
   * @return {module:model/InventoryItem} The populated <code>InventoryItem</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InventoryItem();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('releaseDate'))
        obj.releaseDate = ApiClient.convertToType(data['releaseDate'], 'Date');
      if (data.hasOwnProperty('manufacturer'))
        obj.manufacturer = Manufacturer.constructFromObject(data['manufacturer']);
      if (data.hasOwnProperty('quantity'))
        obj.quantity = Quantity.constructFromObject(data['quantity']);
      if (data.hasOwnProperty('description'))
        obj.description = Description.constructFromObject(data['description']);
      if (data.hasOwnProperty('units'))
        obj.units = Units.constructFromObject(data['units']);
      if (data.hasOwnProperty('bin'))
        obj.bin = Bin.constructFromObject(data['bin']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
InventoryItem.prototype.id = undefined;

/**
 * @member {String} name
 */
InventoryItem.prototype.name = undefined;

/**
 * @member {Date} releaseDate
 */
InventoryItem.prototype.releaseDate = undefined;

/**
 * @member {module:model/Manufacturer} manufacturer
 */
InventoryItem.prototype.manufacturer = undefined;

/**
 * @member {module:model/Quantity} quantity
 */
InventoryItem.prototype.quantity = undefined;

/**
 * @member {module:model/Description} description
 */
InventoryItem.prototype.description = undefined;

/**
 * @member {module:model/Units} units
 */
InventoryItem.prototype.units = undefined;

/**
 * @member {module:model/Bin} bin
 */
InventoryItem.prototype.bin = undefined;

