/*
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Manufacturer model module.
 * @module model/Manufacturer
 * @version 1.0.0
 */
export class Manufacturer {
  /**
   * Constructs a new <code>Manufacturer</code>.
   * @alias module:model/Manufacturer
   * @class
   * @param name {String} 
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>Manufacturer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Manufacturer} obj Optional instance to populate.
   * @return {module:model/Manufacturer} The populated <code>Manufacturer</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Manufacturer();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('homePage'))
        obj.homePage = ApiClient.convertToType(data['homePage'], 'String');
      if (data.hasOwnProperty('phone'))
        obj.phone = ApiClient.convertToType(data['phone'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
Manufacturer.prototype.name = undefined;

/**
 * @member {String} homePage
 */
Manufacturer.prototype.homePage = undefined;

/**
 * @member {String} phone
 */
Manufacturer.prototype.phone = undefined;

