/*
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Quantity model module.
 * @module model/Quantity
 * @version 1.0.0
 */
export class Quantity {
  /**
   * Constructs a new <code>Quantity</code>.
   * @alias module:model/Quantity
   * @class
   * @param quantity {Number} 
   */
  constructor(quantity) {
    this.quantity = quantity;
  }

  /**
   * Constructs a <code>Quantity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Quantity} obj Optional instance to populate.
   * @return {module:model/Quantity} The populated <code>Quantity</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Quantity();
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} quantity
 */
Quantity.prototype.quantity = undefined;

