/*
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Units model module.
 * @module model/Units
 * @version 1.0.0
 */
export class Units {
  /**
   * Constructs a new <code>Units</code>.
   * @alias module:model/Units
   * @class
   * @param units {String} 
   */
  constructor(units) {
    this.units = units;
  }

  /**
   * Constructs a <code>Units</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Units} obj Optional instance to populate.
   * @return {module:model/Units} The populated <code>Units</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Units();
      if (data.hasOwnProperty('units'))
        obj.units = ApiClient.convertToType(data['units'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} units
 */
Units.prototype.units = undefined;

