/*
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SimpleInventoryApi);
  }
}(this, function(expect, SimpleInventoryApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Manufacturer', function() {
      beforeEach(function() {
        instance = new SimpleInventoryApi.Manufacturer();
      });

      it('should create an instance of Manufacturer', function() {
        // TODO: update the code to test Manufacturer
        expect(instance).to.be.a(SimpleInventoryApi.Manufacturer);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property homePage (base name: "homePage")', function() {
        // TODO: update the code to test the property homePage
        expect(instance).to.have.property('homePage');
        // expect(instance.homePage).to.be(expectedValueLiteral);
      });

      it('should have the property phone (base name: "phone")', function() {
        // TODO: update the code to test the property phone
        expect(instance).to.have.property('phone');
        // expect(instance.phone).to.be(expectedValueLiteral);
      });

    });
  });

}));
