/*
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SimpleInventoryApi);
  }
}(this, function(expect, SimpleInventoryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SimpleInventoryApi.AdminsApi();
  });

  describe('(package)', function() {
    describe('AdminsApi', function() {
      describe('addInventory', function() {
        it('should call addInventory successfully', function(done) {
          // TODO: uncomment, update parameter values for addInventory call
          /*
          var opts = {};

          instance.addInventory(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
